/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f7f9fb",
        "primary-container": "#1e3a5f",
        "tertiary-fixed": "#c8e6ff",
        "on-primary-fixed-variant": "#2d486d",
        "inverse-on-surface": "#eff1f3",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-tint": "#455f87",
        "surface-container": "#eceef0",
        "on-secondary-container": "#004a7d",
        "surface-dim": "#d8dadc",
        "primary": "#022448",
        "outline-variant": "#c4c6cf",
        "on-primary-fixed": "#001c3b",
        "on-surface-variant": "#43474e",
        "inverse-primary": "#adc8f5",
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#001e2f",
        "on-secondary-fixed": "#001d36",
        "secondary-container": "#7cbaff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "tertiary": "#00273b",
        "secondary-fixed": "#d1e4ff",
        "secondary-fixed-dim": "#9ecaff",
        "surface-container-highest": "#e0e3e5",
        "secondary": "#0b61a1",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#00497c",
        "tertiary-fixed-dim": "#a7cbe8",
        "on-error": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#264a62",
        "on-primary-container": "#8aa4cf",
        "surface": "#f7f9fb",
        "tertiary-container": "#163d54",
        "primary-fixed-dim": "#adc8f5",
        "on-surface": "#191c1e",
        "outline": "#74777f",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "on-tertiary-container": "#84a8c3"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
